import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
Matrix1 = tf.Variable(tf.random_normal([2,3]))
Matrix2 = tf.Variable(tf.truncated_normal([3,2]))
Result = tf.matmul(Matrix1,Matrix2)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print ('Matrix1:')
    print (sess.run(Matrix1))
    print ('Matrix2:')
    print (sess.run(Matrix2))
    print ('Result:')
    print (sess.run(Result))
Matrix1_Value = tf.random_normal([2,3])
Matrix2_Value = tf.truncated_normal([3,2])
Matrix1 = tf.placeholder(dtype=tf.float32,shape=[2,3])
Matrix2 = tf.placeholder(dtype=tf.float32,shape=[3,2])
Result = tf.matmul(Matrix1,Matrix2)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print ('Matrix1:')
    print (sess.run(Matrix1_Value))
    print ('Matrix2:')
    print (sess.run(Matrix2_Value))
    print ('Result:')
    print (sess.run(Result,feed_dict={Matrix1:sess.run(Matrix1_Value),Matrix2:sess.run(Matrix2_Value)}))
